// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sxrglcrltmmuwhrnzpjo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN4cmdsY3JsdG1tdXdocm56cGpvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA4MjQ5ODcsImV4cCI6MjA1NjQwMDk4N30.YpN5sMyG_Qt50cUKdDJjW6bl4MVXopecos7onFQhxTE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);